#!/usr/bin/env bash
#Prints subdomain info

function dig_site() {
string=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print $4, $5}')
echo "$2 $string" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3'}
}


if [ "$#" == 1 ]
then
    dig_site "$1" "www"
    dig_site "$1" "lb-01"
    dig_site "$1" "web-01"
    dig_site "$1" "web-02"
elif [ "$#" == 2 ]
then
    dig_site "$1" "$2"
fi
