#!/usr/bin/env bash
#copy to remote host using scp

if [[$# -lt 4]]
then
  echo "Usage: 0-transfer_file PATH_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
