#!/usr/bin/env bash
# Script installs and configures nginx then redirects /redirect_me
apt-get update
apt-get -y install nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://vx-underground.org/;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
